seed: 42
split: {train_size: 0.7, val_size: 0.15, test_size: 0.15, seed: 42}
outliers: {grlivarea_max: 4000, saleprice_min: 300000}
cv: {n_splits: 5, n_repeats: 3}
model: {optuna_trials: 60}
clean:
  drop_cols: [Id, Utilities, Street, Condition2, RoofMatl, Heating, PoolQC, MiscFeature]
features:
  drop_after: [GarageArea, GarageYrBlt, PoolArea, MiscVal, LotRatio, IsRemodeled]
preprocess: {skew_threshold: 0.75, min_frequency: 0.01}
mlflow: {tracking_uri: 'sqlite:///mlflow.db', experiment: lifinity}
tune:
  cv_folds: 5
  trials: {Lasso: 60, ElasticNet: 60, XGBoost: 40, CatBoost: 25}
  timeout_sec: 900
final_model:
  type: blend
  name: blend
  params:
    weights: {Lasso: 0.2596586609018729, ElasticNet: 0.2643797339856401, XGBoost: 0.4377247188109414,
      CatBoost: 0.03823688630154574}
    model_params:
      Lasso: {alpha: 0.0006119854691593898}
      ElasticNet: {alpha: 0.0006358358856676254, l1_ratio: 0.6872653200164409}
      XGBoost: {n_estimators: 1476, learning_rate: 0.03262249393408143, max_depth: 3,
        min_child_weight: 4, subsample: 0.8535059794504334, colsample_bytree: 0.32760317883921475,
        reg_lambda: 0.1645820664056707, reg_alpha: 0.0006408000295252277}
      CatBoost: {iterations: 1882, learning_rate: 0.01871879330520506, depth: 4, l2_leaf_reg: 1.1752776200103654,
        random_strength: 1.7563780885296132, bagging_temperature: 0.7824263094276925}
